name: Automated Deployment
on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Make Request
        id: myRequest
        uses: fjogeleit/http-request-action@master
        with:
            url: http://40.112.50.130:9000/hooks/redeploy
            method: 'HEAD'
      - name: Show Response
        run: echo ${{ steps.myRequest.outputs.response }}

